In [1]:
%%capture timeit_results
import numpy as np
%timeit l1=range(1,1000)
%timeit l2=np.arange(1,1000)


In [2]:
print timeit_results

100000 loops, best of 3: 12 us per loop
The slowest run took 14.30 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.43 us per loop



In [4]:
l1=[1,2,3,4,5,6,7]
l2=[8,9,10,11,12,13,14]
arr1=np.array(l1)
arr2=np.array(l2)

In [5]:
%%capture timeit_results
%timeit l3=[i+j for i,j in zip(l1,l2)]
%timeit l4=arr1+arr2

In [8]:
print timeit_results

The slowest run took 7.29 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.8 us per loop
The slowest run took 41.90 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 717 ns per loop



In [9]:
np.array([l1,l2])

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
sample_data = np.random.random((2,3))

In [13]:
sample_data

array([[ 0.2618987 ,  0.76951598,  0.31773158],
       [ 0.32301147,  0.97059884,  0.45814108]])

In [14]:
np.max(sample_data)

0.97059884422430009

In [15]:
np.max(sample_data,axis=0)

array([ 0.32301147,  0.97059884,  0.45814108])

In [16]:
np.max(sample_data,axis=1)

array([ 0.76951598,  0.97059884])

In [17]:
np.reshape(sample_data,(3,2))

array([[ 0.2618987 ,  0.76951598],
       [ 0.31773158,  0.32301147],
       [ 0.97059884,  0.45814108]])

In [18]:
sample_data

array([[ 0.2618987 ,  0.76951598,  0.31773158],
       [ 0.32301147,  0.97059884,  0.45814108]])

In [19]:
data=np.random.random((5,6))

In [20]:
data

array([[ 0.85888778,  0.51925984,  0.34221498,  0.76313219,  0.92476409,
         0.13572851],
       [ 0.90139065,  0.99860511,  0.75534595,  0.5724616 ,  0.76695632,
         0.95582629],
       [ 0.14786012,  0.61487062,  0.52772141,  0.13632225,  0.8793729 ,
         0.40010857],
       [ 0.76869054,  0.83515778,  0.99910526,  0.96295646,  0.61456529,
         0.0036595 ],
       [ 0.5492175 ,  0.37258578,  0.24292127,  0.42207688,  0.75830648,
         0.54547003]])

In [23]:
data[1:4,0:2]

array([[ 0.90139065,  0.99860511],
       [ 0.14786012,  0.61487062],
       [ 0.76869054,  0.83515778]])

In [24]:
import matplotlib.pyplot as plt

In [25]:
fig = plt.figure()
axes = fig.add_subplot(111)
x=[0,1,2,3,4,5,6,7]
y=[10,3,4,6,23,56,67,89]
axes.plot(x,y)
plt.show()

In [27]:
# two lines
fig = plt.figure()
axes = fig.add_subplot(111)
x=[0,1,2,3,4,5,6,7]
y=[10,3,4,6,23,56,67,89]
y1=[7,12,34,5,67,8,90,90]
axes.plot(x,y)
axes.plot(x,y1)
plt.show()

In [32]:
# two lines
fig = plt.figure()
axes = fig.add_subplot(111)
x=[0,1,2,3,4,5,6,7]
y=[10,3,4,6,23,56,67,89]
y1=[7,12,34,5,67,8,90,90]
axes.set_xlabel("x axis")
axes.set_ylabel("y axis")
axes.plot(x,y)
axes.plot(x,y1,color="red",linestyle="dashed", linewidth=3)
plt.show()

In [34]:
pwd

u'/home/shiva/Documents/DRF_Analytics'